// let fullName = "Faisal Saeed";
// console.log(fullName);
// let firstName = ("Mian ");
// let secondName = ("Faisal ");
// let thirdName = ("Saeed ");
// console.log(firstName + secondName + thirdName);
// let firstName = "Mian";
// let secondName = "Faisal";
// let thirdName = "Saeed";
// console.log(firstName + " " + secondName + " " + thirdName);
// let firstName = `Ali`;
// let myAge = 23; // Number
// console.log (typeof firstName);
// console.log (typeof myAge);
// let ismarried = false;
// console.log (ismarried);
// let isLikejavascript = true;
// console.log (isLikejavascript);
var isLiketypescript = false;
console.log(isLiketypescript);
